FROM jenkins/inbound-agent:latest

USER root

# Instala herramientas necesarias, incluido docker-cli, maven y kubectl
RUN apt-get update && apt-get install -y \
    curl \
    apt-transport-https \
    ca-certificates \
    gnupg \
    git \
    maven \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sLO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm kubectl

# Crea grupo docker con GID 999 (el mismo que el del host para el socket docker)
RUN groupadd -g 999 docker || true

# Agrega usuario jenkins al grupo docker
RUN usermod -aG docker jenkins

USER jenkins
